import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import SideBar from '@/components/SideBar';
import Header from '@/components/Header';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Deview',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={openSans.className}>
      <body>
        <div className='flex min-h-screen overflow-hidden'>
          <div className='hidden md:block w-64 shrink-0'>
            <SideBar />
          </div>
          <div className='flex-1 flex flex-col'>
            <Header />
            <main className='flex-1 p-4 overflow-y-auto'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
