import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import SideBar from '@/components/SideBar';
import Header from '@/components/Header';
import AuthContext from '@/context/AuthContext';
import { auth } from '@/auth';
import Welcome from '@/components/Welcome';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Deview',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user;
  return (
    <html lang='en' className={openSans.className}>
      <body className='overflow-hidden'>
        <AuthContext>
          <div className='flex h-screen'>
            <div className='hidden md:block w-64 shrink-0'>
              <SideBar />
            </div>
            <div className='flex-1 flex flex-col'>
              <Header />
              {user ? (
                <main className='flex-1 p-4 overflow-y-auto'>{children}</main>
              ) : (
                <div className='flex-1 overflow-y-auto'>
                  <Welcome />
                </div>
              )}
            </div>
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
